[project]
site_name = "mailcow: dockerized documentation"
site_url = "https://docs.mailcow.email/"
copyright = "Copyright &copy; <script>document.write(new Date().getFullYear())</script> mailcow Team & Community"
repo_name = "mailcow/mailcow-dockerized"
repo_url = "https://github.com/mailcow/mailcow-dockerized"
edit_uri = "../mailcow-dockerized-docs/edit/master/docs/"
extra_css = ["assets/stylesheets/extra.css"]
extra_javascript = ["assets/javascripts/client.js"]
docs_dir = "docs"


nav = [
  {"Information & Support" = "index.md"},
  {"Get started" = [
    {"Prepare your system" = "getstarted/prerequisite-system.md"},
    {"DNS setup" = "getstarted/prerequisite-dns.md"},
    {"Install mailcow" = "getstarted/install.md"}
	]},
  {"Maintaining mailcow" = [
    {"Update" = "maintenance/update.md"},
    {"Migration" = "maintenance/migration.md"},
    {"Deinstallation" = "maintenance/deinstall.md"}
	]},
  {"Backup & Restore" = [
    {"Component backup & restore" = [
      {"Backup" = "backup_restore/b_n_r-backup.md"},
      {"Restore" = "backup_restore/b_n_r-restore.md"}
	  ]},
    {"Cold-standby (rolling backup)" = ["backup_restore/b_n_r-coldstandby.md"]},
    {"Manual backups" = [
      {"Maildir" = "backup_restore/b_n_r-backup_restore-maildir.md"},
      {"MySQL (mysqldump)" = "backup_restore/b_n_r-backup_restore-mysql.md"}
	  ]},
    {"mailcow-internal backups" = [
      {"Recover accidentally deleted data" = "backup_restore/b_n_r-accidental_deletion.md"}
	]},
  {"Post Installation Tasks" = [
    {"Advanced SSL" = "post_installation/firststeps-ssl.md"},
    {"Authorize Watchdog and Bounce Mails" = "post_installation/firststeps-authorize_watchdog_and_bounces.md"},
    {"Disable IPv6" = "post_installation/firststeps-disable_ipv6.md"},
    {"DMARC Reporting" = "post_installation/firststeps-dmarc_reporting.md"},
    {"IP bindings" = "post_installation/firststeps-ip_bindings.md"},
    {"Local MTA on Docker host" = "post_installation/firststeps-local_mta.md"},
    {"Logging" = "post_installation/firststeps-logging.md"}
	]},
    {"Reverse Proxy" = [
      {"Overview" = "post_installation/reverse-proxy/r_p.md"},
      {"Apache 2.4" = "post_installation/reverse-proxy/r_p-apache24.md"},
      {"Nginx" = "post_installation/reverse-proxy/r_p-nginx.md"},
      {"HAProxy (community supported)" = "post_installation/reverse-proxy/r_p-haproxy.md"},
      {"Traefik v2 (community supported)" = "post_installation/reverse-proxy/r_p-traefik2.md"},
      {"Caddy v2 (community supported)" = "post_installation/reverse-proxy/r_p-caddy2.md"}
	  ]},
    {"SNAT" = "post_installation/firststeps-snat.md"},
    {"Sync job migration" = "post_installation/firststeps-sync_jobs_migration.md"}
    ]},
  {"Models" = [
    {"ACL" = "models/model-acl.md"},
    {"Password hashing" = "models/model-passwd.md"},
    {"Sender and receiver model" = "models/model-sender_rcv.md"}
	]},
  {"General Troubleshooting" = [
    {"Introduction" = "troubleshooting/debug.md"},
    {"Admin login to SOGo" = "troubleshooting/debug-admin_login_sogo.md"},
    {"Advanced = Find memory leaks in Rspamd" = "troubleshooting/debug-rspamd_memory_leaks.md"},
    {"Attach to a Container" = "troubleshooting/debug-attach_service.md"},
    {"Common Problems" = "troubleshooting/debug-common_problems.md"},
    {"Logs" = "troubleshooting/debug-logs.md"},
    {"Manual MySQL upgrade" = "troubleshooting/debug-mysql_upgrade.md"},
    {"Recover crashed Aria storage engine" = "troubleshooting/debug-mysql_aria.md"},
    {"Remove Persistent Data" = "troubleshooting/debug-rm_volumes.md"},
    {"Resend Quarantine Notifications" = "troubleshooting/debug-resend-quarantine-notifications.md"},
    {"Reset Passwords (incl. SQL)" = "troubleshooting/debug-reset_pw.md"},
    {"Reset TLS certificates" = "troubleshooting/debug-reset_tls.md"}
	]},
  {"Manual/Guides/Examples" = [
    {"mailcow UI" = [
      {"Blacklist / Whitelist" = "manual-guides/mailcow-UI/u_e-mailcow_ui-bl_wl.md"},
      {"Configuration" = "manual-guides/mailcow-UI/u_e-mailcow_ui-config.md"},
      {"CSS overrides" = "manual-guides/mailcow-UI/u_e-mailcow_ui-css.md"},
      {"Forgot Password Feature" = "manual-guides/mailcow-UI/u_e-mailcow_ui-forgot_password.md"},
      {"Netfilter" = "manual-guides/mailcow-UI/u_e-mailcow_ui-netfilter.md"},
      {"Notification templates" = "manual-guides/mailcow-UI/u_e-mailcow_ui-notification-templates.md"},
      {"Pushover" = "manual-guides/mailcow-UI/u_e-mailcow_ui-pushover.md"},
      {"Spamfilter" = "manual-guides/mailcow-UI/u_e-mailcow_ui-spamfilter.md"},
      {"Sub-addressing" = "manual-guides/mailcow-UI/u_e-mailcow_ui-sub_addressing.md"},
      {"Tags (for Domains and Mailboxes)" = "manual-guides/mailcow-UI/u_e-mailcow_ui-tags.md"},
      {"Temporary email aliases" = "manual-guides/mailcow-UI/u_e-mailcow_ui-spamalias.md"},
      {"Two-Factor Authentication" = "manual-guides/mailcow-UI/u_e-mailcow_ui-tfa.md"},
      {"WebAuthn / FIDO2" = "manual-guides/mailcow-UI/u_e-mailcow_ui-fido.md"}
	  ]},
    {"Postfix" = [
      {"Unauthenticated Relaying" = "manual-guides/Postfix/u_e-postfix-unauthenticated-relaying.md"},
      {"Custom transport maps" = "manual-guides/Postfix/u_e-postfix-custom_transport.md"},
      {"Customize/Expand main.cf" = "manual-guides/Postfix/u_e-postfix-extra_cf.md"},
      {"Disable Sender Addresses Verification" = "manual-guides/Postfix/u_e-postfix-disable_sender_verification.md"},
      {"Hardening Ciphers" = "manual-guides/Postfix/u_e-postfix-harden_ciphers.md"},
      {"Max. message size (attachment size)" = "manual-guides/Postfix/u_e-postfix-attachment_size.md"},
      {"Relayhosts" = "manual-guides/Postfix/u_e-postfix-relayhost.md"},
      {"Statistics with pflogsumm" = "manual-guides/Postfix/u_e-postfix-pflogsumm.md"},
      {"Whitelist IP in Postscreen" = "manual-guides/Postfix/u_e-postfix-postscreen_whitelist.md"}
	  ]},
    {"Unbound" = [
      {"Using an external DNS service" = "manual-guides/Unbound/u_e-unbound-fwd.md"}
	  ]},
    {"Dovecot" = [
      {"Customize/Expand dovecot.conf" = "manual-guides/Dovecot/u_e-dovecot-extra_conf.md"},
      {"Enable any ACL settings" = "manual-guides/Dovecot/u_e-dovecot-any_acl.md"},
      {"Expunge a Users mails" = "manual-guides/Dovecot/u_e-dovecot-expunge.md"},
      {"Full-Text Search" = "manual-guides/Dovecot/u_e-dovecot-fts.md"},
      {"Hardening Ciphers" = "manual-guides/Dovecot/u_e-dovecot-harden_ciphers.md"},
      {"IMAP IDLE interval" = "manual-guides/Dovecot/u_e-dovecot-idle_interval.md"},
      {"Lazy Expunge (Dovecot Plugin)" = "manual-guides/Dovecot/u_e-dovecot-lazy_expunge.md"},
      {"Mail crypt" = "manual-guides/Dovecot/u_e-dovecot-mail-crypt.md"},
      {"More Examples with DOVEADM" = "manual-guides/Dovecot/u_e-dovecot-more.md"},
      {"Move Maildir (vmail)" = "manual-guides/Dovecot/u_e-dovecot-vmail-volume.md"},
      {"Performance Optimizations" = "manual-guides/Dovecot/u_e-dovecot-performance.md"},
      {"Public folders" = "manual-guides/Dovecot/u_e-dovecot-public_folder.md"},
      {"Static master user" = "manual-guides/Dovecot/u_e-dovecot-static_master.md"},
      {"Vacation replies for catchall addresses" = "manual-guides/Dovecot/u_e-dovecot-catchall_vacation.md"}
	  ]},
    {"Nginx" = [
      {"Create subdomain webmail.example.org" = "manual-guides/Nginx/u_e-nginx_webmail-site.md"},
      {"Custom sites" = "manual-guides/Nginx/u_e-nginx_custom.md"}
	  ]},
    {"Watchdog" = [
      {"Thresholds" = "manual-guides/Watchdog/u_e-watchdog-thresholds.md"}
	  ]},
    {"Redis" = "manual-guides/Redis/u_e-redis.md"},
    {"Rspamd" = [
      {"General Settings" = "manual-guides/Rspamd/u_e-rspamd-general.md"},
      {"Tweaks" = "manual-guides/Rspamd/u-e-rspamd-tweaks.md"},
      {"Work with Spam Data" = "manual-guides/Rspamd/u-e-rspamd-work-with-spamdata.md"},
      {"Disable Greylisting" = "manual-guides/Rspamd/u_e-rspamd-disable-greylisting.md"},
      {"Add Additional Modules" = "manual-guides/Rspamd/u-e-rspamd-add-additional-modules.md"}
	  ]},
    {"ClamAV" = [
      {"Whitelist" = "manual-guides/ClamAV/u_e-clamav-whitelist.md"},
      {"Additional Databases" = "manual-guides/ClamAV/u_e-clamav-additional_dbs.md"}
	  ]},
    {"SOGo" = "manual-guides/SOGo/u_e-sogo.md"},
    {"Docker" = [
      {"Customize Dockerfiles" = "manual-guides/Docker/u_e-docker-cust_dockerfiles.md"}
	  ]},
    {"Why unbound?" = "manual-guides/u_e-why_unbound.md"},
    {"Autodiscover / Autoconfig" = "manual-guides/u_e-autodiscover_config.md"},
    {"Redirect HTTP to HTTPS" = "manual-guides/u_e-80_to_443.md"},
    {"Re-enable TLS 1.0 and TLS 1.1" = "manual-guides/u_e-reeanble-weak-protocols.md"},
    {"Run scripts before and after updates" = "manual-guides/u_e-update-hooks.md"}
	]},
  {"Client Configuration" = [
    {"Overview" = "client/client.md"},
    {"Android" = "client/client-android.md"},
    {"Apple macOS / iOS" = "client/client-apple.md"},
    {"eM Client" = "client/client-emclient.md"},
    {"KDE Kontact" = "client/client-kontact.md"},
    {"Microsoft Outlook" = "client/client-outlook.md"},
    {"Mozilla Thunderbird" = "client/client-thunderbird.md"},
    {"Windows Mail" = "client/client-windows.md"},
    {"Manual configuration" = "client/client-manual.md"}
	]},
  {"Third party apps" = [
    {"Borgmatic Backup" = "third_party/borgmatic/third_party-borgmatic.md"},
    {"CheckMK"  = "third_party/checkmk/u_e-checkmk.md"},
    {"Exchange Hybrid Setup" = "third_party/exchange_onprem/third_party-exchange_onprem.md"},
    {"Gitea" = "third_party/gitea/third_party-gitea.md"},
    {"Gogs" = "third_party/gogs/third_party-gogs.md"},
    {"Mailman 3" = "third_party/mailman3/third_party-mailman3.md"},
    {"Mailpiler Integration" = "third_party/mailpiler/third_party-mailpiler_integration.md"},
    {"Nextcloud" = "third_party/nextcloud/third_party-nextcloud.md"},
    {"Portainer" = "third_party/portainer/third_party-portainer.md"}
	]}
]


[project.theme]
variant = "classic" # or modern
logo = "assets/images/logo.svg"
favicon = "assets/images/favicon.png"
language = "en"
features = [
  "announce.dismiss",
  "navigation.top",
  "navigation.tracking",
  "content.tabs.link",
  "content.tooltips",
  "content.code.copy",
  "search.highlight"
]

# Palette toggle for automatic mode
[[project.theme.palette]]
media = "(prefers-color-scheme)"
toggle.icon = "material/brightness-auto"
toggle.name = "Switch to light mode"

# Palette toggle for light mode
[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "material/brightness-7"
toggle.name = "Switch to dark mode"

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "material/brightness-4"
toggle.name = "Switch to system preference"

[project.extra]
alternate = [
    { name = "English", link = "/", lang = "en" },
    { name = "Deutsch", link = "/de/", lang = "de" }
]

[[project.extra.social]]
icon = "fontawesome/solid/globe"
link = "https://mailcow.email"
[[project.extra.social]]
icon = "fontawesome/brands/github-alt"
link = "https://github.com/mailcow"
[[project.extra.social]]
icon = "fontawesome/brands/x-twitter"
link = "https://x.com/mailcow_email"
[[project.extra.social]]
icon = "fontawesome/brands/mastodon"
link = "https://mailcow.social/@doncow"

[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji"
emoji_generator = "zensical.extensions.emoji.to_svg"
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
[project.markdown_extensions.pymdownx.superfences]
[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.tilde]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.admonition]
[project.markdown_extensions.pymdownx.betterem]
[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true
[project.markdown_extensions.toc]
permalink = true
[project.markdown_extensions.footnotes]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.abbr]

